# Storage for all packages
storage: ./storage

listen:
  - 0.0.0.0:4873

logs:
  - {type: stdout, format: pretty, level: info}

auth:
  htpasswd:
    file: ./htpasswd

# A list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    timeout: 10s
    maxage: 10m
    
packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '*':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # Allow authenticated users to publish packages
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

